# -*- coding: utf-8 -*-
"""ExerciciosFlavio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dKazLZm1v_lU4jLXyo2kgAcNlb0VEEpd
"""

#Média de Notas

somatotal = 0
for i in range(3):
  nota = float(input(f"\nDigite a {i + 1}ª nota: "))
  somatotal = somatotal + nota

media = somatotal / 3

print(f"\nMédia: {media:.2f}")

#Tabuada
numero = int(input(f"Digite um numero: "))

for i in range(11):
  tabuada = numero * i

  print(f"\n{numero} X {i} = {tabuada}")

#Calculadora

numero1 = int(input("Digite o 1º numero: "))
numero2 = int(input("\nDigite o 2º numero: "))

for i in range(100000):

  opcao = int(input("\nEscolha a Operação: \n(1) - Adição \n(2) - Subtração \n(3) - Multiplicação \n(4) - Divisão \n\n"))

  if opcao == 1:
    print(f"\nAdição: {numero1 + numero2}")
    break
  elif opcao == 2:
    print(f"\nSubtração: {numero1 - numero2}")
    break
  elif opcao == 3:
    print(f"\nMultiplicação: {numero1 * numero2}")
    break
  elif opcao == 4:
    print(f"\nDivisão: {numero1 / numero2}")
    break
  else:
    print("\nOpção invalida!!!")

#Meses

for i in range(1000000):
  mes = int(input("\nDigite um número de 1 à 12: "))
  if mes >= 1 and mes <= 12:
    if mes == 1:
      print("\nJaneiro")
      break
    elif mes == 2:
      print("\nFevereiro")
      break
    elif mes == 3:
      print("\nMarço")
      break
    elif mes == 4:
      print("\nAbril")
      break
    elif mes == 5:
      print("\nMaio")
      break
    elif mes == 6:
      print("\nJunho")
      break
    elif mes == 7:
      print("\nJulho")
      break
    elif mes == 8:
      print("\nAgosto")
      break
    elif mes == 9:
      print("\nSetembro")
      break
    elif mes == 10:
      print("\nOutubro")
      break
    elif mes == 11:
      print("\nNovembro")
      break
    elif mes == 12:
      print("\nDezembro")
      break
  else:
    print("\nDigito Invalido!!!")

#Tabela de lanches

valor = 0
valorTotal = 0

for i in range(1000000):
  print("\nEspecificação   | Código | Preço \n\nCachorro Quente |   100  | 1,20 \nBauru Simples   |   101  | 1,30 \nBauru com Ovo   |   102  | 1,50 \nHamburguer      |   103  | 1,20 \nCheeseburguer   |   104  | 1,70 \nSuco            |   105  | 2,20 \nRefrigerante    |   106  | 1,00")
  codigo = int(input("\nDigite o código desejado: "))
  if codigo == 100:
    valor = 1.20
  elif codigo == 101:
    valor = 1.30
  elif codigo == 102:
    valor = 1.50
  elif codigo == 103:
    valor = 1.20
  elif codigo == 104:
    valor = 1.70
  elif codigo == 105:
    valor = 2.20
  elif codigo == 106:
    valor = 1.00
  else:
    print("\nDigito invalido!!!")

  valorTotal = valorTotal + valor

  tentar = input("\nDeseja parar de pedir? \nSim     Não \n\n").lower().strip()
  if tentar == "sim":
    print(f"\nSeu pedido custou {valorTotal:.2f} \nObrigado pela atenção!!!")
    break

#Olimpiada Brasileira de Informática

for i in range(10000000):
  nota = float(input("\nDigite a nota: "))
  if nota >= 86 and nota <= 100 :
    print ("\nNota A")
    break
  elif nota >= 61 and nota <= 85:
    print ("\nNota B")
    break
  elif nota >= 36 and nota <= 60:
    print ("\nNota C")
    break
  elif nota >= 1 and nota <=35:
    print ("\nNota D")
    break
  elif nota == 0 :
    print ("\nNota E")
    break
  else:
    print ("\nDigito Invalido!!!")

#Raiz quadrada

import numpy as np

num = float(input("Digite um número: "))
raiz = np.sqrt(num)
print(f"{raiz:.2f}")

#Celsius e Fahrenheit

celsius = int(input("Digite a Temperatura em Celsius: "))

fahrenheit = celsius * (9 / 5) + 32

print(f"\nTemperatura em Fahrenheit: {fahrenheit}")

#Fórmula de Bhaskara

import math

a = float(input("Digite o valor de A: "))

if a > 0:
  b = float(input("\nDigite o valor de B: "))
  c = float(input("\nDigite o valor de C: "))

  delta = b ** 2 - 4 * a * c
  if delta < 0:
    print("\nA equação não possui raizes reais")

  elif delta == 0:
        raiz = -b / (2 * a)

        print(f"\nA equação possui uma raiz real: {raiz:.2f}")
  else:
        raiz1 = (-b + math.sqrt(delta)) / (2 * a)
        raiz2 = (-b - math.sqrt(delta)) / (2 * a)

        print(f"\nA equação possui duas raízes reais: {raiz1:.2f} e {raiz2:.2f}")
else:
  print("\nNão é uma equação de 2º grau")

#Numero maior

numeros = []

for i in range(3):
  numeros.append(int(input(f"\nDigite o {i+1}º numero: ")))

print(f"\nO maior numero: {max(numeros)}")

#Numero maior e menor

numeros = []

for i in range(3):
  numeros.append(int(input(f"\nDigite o {i+1}º numero: ")))

print(f"\nO maior numero: {max(numeros)} \nO menor numero: {min(numeros)}")

#Triangulo

for i in range(1000000):

  lado1 = int(input("\nDigite o 1º lado do triângulo: "))
  lado2 = int(input("\nDigite o 2º lado do triângulo: "))
  lado3 = int(input("\nDigite o 3º lado do triângulo: "))

  if lado1 > 0 and lado2 > 0 and lado3 > 0:

    if lado1 == lado2 and lado2 == lado3:
      print("\nTriângulo equilátero")
      break
    elif lado1 == lado2 or lado1 == lado3 or lado2 == lado3:
      print("\nTriângulo isósceles")
      break
    else:
      print("\nTriângulo escaleno")
      break
  else:
    print("\nMedidas nulas")

#Senha e Login
for i in range(10000000):
  login = input("\nDigite seu Login: ").strip()
  senha = input("\nDigite sua senha: ").strip()
  confSenha = input("\nConfirme sua senha: ").strip()
  if senha == confSenha:
    if login == "user" and senha == "user":
      print("\nBem vindo!!!")
      break
    else:
      print("\nEntrada negada!!!")
      break
  else:
    print("\nSenhas diferentes!")

#Numeros iguais

numero1 = int(input("\nDigite o 1º numero: "))
numero2 = int(input("\nDigite o 2º numero: "))

if numero1 > numero2:
  print(f"\n1º numero maior")
elif numero1 < numero2:
  print(f"\n2º numero maior")
else:
  print(f"\nAmbos são iguais")

nome = input("\nDigite seu Nome: ").strip()
sobrenome = input("\nDigite seu Sobrenome: ").strip()

print(f"\nNome e Sobrenome: {nome} {sobrenome}")