# -*- coding: utf-8 -*-
"""exerciciosWhile.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OVEOkK33HRai4OCiP4E3JRcIUlgLzLhW
"""

#Numero de 1 à 10

contador = 0

while contador <= 9:
  contador = contador + 1
  print(f"\n{contador}")

#Numero par de 1 à 20

contador = 0

while contador <= 19:
  contador = contador + 2
  print(f"\n {contador}")

#Contador de maioridade

qtd_pessoas = 0
contador = 0
while contador < 5:
  idade = int(input(f"\nDigite a idade da {contador + 1}ª pessoa: "))
  if idade > 18:
    qtd_pessoas += 1
  contador += 1
print(f"\nNúmero de pessoas Maiores de idade: {qtd_pessoas}")

#Tabuada

contador = 0

while True:
  numero = int(input("\nDigite um numero de 1 à 10: "))
  if numero > 10:
    print ("\nDigito invalido")
  else:
    while contador < 101:
      contador = contador + 1
      tabuada = numero * contador
      print(f"\n{numero} X {contador} = {tabuada}")
    break

#Senhas

while True:
  senha = int(input("Digite os 4 numeros da senha: "))
  senha = int(input("Digite novamente: "))
  if senha == 1001:
    print("Senha Correta")
  else:
    print("Senha Incorreta")
  break